server.port=8080
spring.application.name=meow-booms
server.servlet.context-path=/play

spring.profiles.active=dev

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

spring.jackson.time-zone=Asia/Bangkok

