#host
host.ip = 178.128.84.237
host.protocol = http

#CACH
logging.level.org.springframework.cache=TRACE
cache.ttl-hr = 24

# Database connection
spring.datasource.url=${MSSQL_URL}
spring.datasource.username=${MSSQL_USERNAME}
spring.datasource.password=${MSSQL_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.legacy_limit_handler=true 
spring.jpa.hibernate.ddl-auto= none

#-------------------------------------------------------------------#
# Email                                                             #
#-------------------------------------------------------------------#
mail.from=hris <noreply.zti@gmail.com>
mail.sender=noreply.zti@gmail.com
mail.user=${EMAIL_USERNAME}
mail.password=${EMAIL_PASSWORD}
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

#storage
dir.attach = attach

#epayment
epayment.url = https://epayment.dld.go.th/sign-in

# Session Cookie Configuration
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.path=/emm-domestic
server.servlet.session.timeout=30m
server.servlet.session.tracking-modes=cookie

#check Local Dev
is.local.dev=true

# Portal Integration
portal.base-url=https://emove.ztidev.com/emm-portal
portal.token-validation-endpoint=/api/v1/sso/valid
# validate Portal
portal.validation.enabled=true
# Cache validate
portal.validation.cache-enabled=false
portal.validation.cache-ttl=60

# Graph hopper


graphhopper.osm.path=/data/osm-data/thailand-latest.osm.pbf
graphhopper.graph.location=/data/osm-data/graph-cache

#-------------------------------------------------------------------#
# Thymeleaf Config                                                  #
# Hot reload                                                        #
#-------------------------------------------------------------------#
spring.thymeleaf.cache=true
#spring.thymeleaf.prefix=file:src/main/resources/templates/
#spring.web.resources.static-locations=file:src/main/resources/static/

spring.thymeleaf.prefix=classpath:/templates/
spring.web.resources.static-locations=classpath:/static/
#spring.thymeleaf.cache.period=0
